 language: node_js
 node_js: "stable"

 before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: latest
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

env:
  IMBB_KEY: ${{ secrets.IMBB_KEY }}

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

install:
  - npm install

script: 
  - npm run test --imbb_key=$IMBB_KEY